### ISSUE TITLE
Playing in background not working in ios 14

### ISSUE THREAD

**Issue by nhatduong** [AhmadAmri/AQPlayer#6]
hello,

I tested on ios 14 and playing in the background not working. please help me.

Thank you.

**Comment by AhmadAmri** [comment]
Hi @nhatduong, 
Sorry that I couldn't reply to you earlier. Did it work for you? 

I didn't check the example that coming with the library, but it is working in the apps that already using it.

**Comment by nhatduong** [comment]
hi @AhmadAmri ,

Thank you for the reply.
I played an mp3 link and it worked, but I used an mp4 link it didn't work for me in the background. Can you help me?

Thank you!

**Comment by AhmadAmri** [comment]
You're welcome @nhatduong 

I didn't use it for mp4 before. But I just tried it out, and it worked fine!

What I did is changing the urls in the example to links from this list: ([public test videos](https://gist.github.com/jsturgis/3b19447b304616f18657)).
The audio worked in the background and I could manage it from the lock screen.

Make sure to check "**Audio, AirPlay and Picture in Picture**" in "**Background Modes**" in your app setting.

**Comment by nhatduong** [comment]
Hi @AhmadAmri,

Thank you for the reply.

I selected "Audio, AirPlay and Picture in Picture" in "Background Mode".
If I use mp4 and don't use AVPlayerLayer then it works with background for me, but if I use AVPlayerLayer to render video on custom view, it doesn't work in background.

Thank you.

**Comment by AhmadAmri** [comment]
The issue seems related to this documentation: https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/creating_a_basic_video_player_ios_and_tvos/playing_audio_from_a_video_asset_in_the_background

It says that you have to remove the player from the AVPlayerLayer before entering background and reattach it again when return to foreground.

I didn't try it myself; so let me know if this work for you, or if you have this implemented already.


PS: If you want to keep the video playing "picture in picture", you may use a [AVPlayerViewController](https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_in_a_standard_player) and set "playerController.allowsPictureInPicturePlayback", or [adopt picture_in_picture in a custom player](https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_in_a_custom_player)

**Comment by nhatduong** [comment]
Hi @AhmadAmri,

Thank you for the reply.

I followed the documentation: https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/creating_a_basic_video_player_ios_and_tvos/playing_audio_from_a_video_asset_in_the_background , but it looks like the problem is not fixed, it doesn't work.

Another problem, when I debug, I see when the application goes into the background, the audio is interrupted and the function:
func aQPlayerManager (_ playerManager: AQPlayerManager, statusDidChange status: AQPlayerStatus) {
    ///Returns the pause event.
}
Can you help me ?

Thank you.

**Comment by AhmadAmri** [comment]
Hi @nhatduong 

Try to move detaching the player to "applicationWillResignActive" function.

If it didn't work; could you share the snippet code of how you attaching the player to the AVPlayerLayer? So I can try it and check the issue.

Good Luck :)

**Comment by AhmadAmri** [comment]
Hi @nhatduong 

For "iOS 13+" I guess you should use "SceneDelegate" function "[scenedidenterbackground](https://developer.apple.com/documentation/uikit/uiscenedelegate/3197917-scenedidenterbackground?language=objc)"
If it didn't work you, Try to move detaching the player to "applicationWillResignActive" or "sceneWillResignActive".

If all of these didn't work; could you share the snippet code of how you attaching the player to the AVPlayerLayer? So I can try it and check the issue.

Good Luck :)

**Comment by nhatduong** [comment]
Thank you very much. My app https://apps.apple.com/vn/app/drumtify-music-for-life/id1530173879
